{
 "title": "noti",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_NOTI", "label": "data source", "query": "graphite" }
  ]
 },
 "panels": [
  {
   "title": "HTTP Requests (Per Second)",
   "type": "graph",
   "description": "Illustrates the various HTTP methods used for the HTTP requests, as well as the total requests.",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "alias(transformNull(perSecond(noti.io.dropwizard.jetty.MutableServletContextHandler.get-requests.count)), \"GET\")"
    },
    {
     "target": "alias(transformNull(perSecond(noti.io.dropwizard.jetty.MutableServletContextHandler.head-requests.count)), \"HEAD\")"
    },
    {
     "target": "alias(transformNull(perSecond(noti.io.dropwizard.jetty.MutableServletContextHandler.post-requests.count)), \"POST\")"
    },
    {
     "target": "alias(transformNull(perSecond(noti.io.dropwizard.jetty.MutableServletContextHandler.options-requests.count)), \"OPTIONS\")"
    },
    {
     "target": "alias(transformNull(perSecond(noti.io.dropwizard.jetty.MutableServletContextHandler.delete-requests.count)), \"DELETE\")"
    },
    {
     "target": "alias(transformNull(perSecond(noti.io.dropwizard.jetty.MutableServletContextHandler.put-requests.count)), \"PUT\")"
    },
    {
     "target": "alias(transformNull(perSecond(noti.io.dropwizard.jetty.MutableServletContextHandler.requests.count)), \"total\")"
    },
    {
     "target": "noti.io.dropwizard.jetty.MutableServletContextHandler.select metric"
    }
   ]
  },
  {
   "title": "HTTP Status Codes (Per Second)",
   "type": "graph",
   "description": "Displays the various HTTP response status codes per second.",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "alias(perSecond(transformNull(noti.io.dropwizard.jetty.MutableServletContextHandler.1xx-responses.count)), \"1XX\")"
    },
    {
     "target": "alias(perSecond(transformNull(noti.io.dropwizard.jetty.MutableServletContextHandler.2xx-responses.count)), \"2XX\")"
    },
    {
     "target": "alias(perSecond(transformNull(noti.io.dropwizard.jetty.MutableServletContextHandler.3xx-responses.count)), \"3XX\")"
    },
    {
     "target": "alias(perSecond(transformNull(noti.io.dropwizard.jetty.MutableServletContextHandler.4xx-responses.count)), \"4XX\")"
    },
    {
     "target": "alias(perSecond(transformNull(noti.io.dropwizard.jetty.MutableServletContextHandler.5xx-responses.count)), \"5XX\")"
    }
   ]
  },
  {
   "title": "HTTP Response Latency (Per Second)",
   "type": "graph",
   "description": "The amount of latency for each HTTP response per second.",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "alias(transformNull(perSecond(noti.io.dropwizard.jetty.MutableServletContextHandler.requests.p99)), \"P99\")"
    },
    {
     "target": "alias(transformNull(perSecond(noti.io.dropwizard.jetty.MutableServletContextHandler.requests.p95)), \"P95\")"
    },
    {
     "target": "alias(transformNull(perSecond(noti.io.dropwizard.jetty.MutableServletContextHandler.requests.max)), \"max\")"
    },
    {
     "target": "alias(transformNull(perSecond(noti.io.dropwizard.jetty.MutableServletContextHandler.requests.mean)), \"mean\")"
    },
    {
     "target": "alias(transformNull(perSecond(noti.io.dropwizard.jetty.MutableServletContextHandler.requests.p50)), \"P50\")"
    }
   ]
  }
 ]
}