database:
  name: ${DB_NAME:-noti}
  host: ${DB_HOST:-localhost}
  port: ${DB_PORT:-3306}
  user: ${DB_USER}
  password: ${DB_PASSWORD}
  useSSL: false
  useLegacyDatetimeCode: false

sms:
  accountSID: ${SMS_ACCOUNT_SID}
  authToken: ${SMS_ACCOUNT_AUTH_TOKEN}

jaeger:
  serviceName: noti

logging:
  level: INFO

metrics:
  frequency: 1 second
  reporters:
    - type: graphite
      host: localhost
      port: 2003
      #prefix: <prefix>
