database:
  name: ${DB_NAME:-noti}
  host: ${DB_HOST:-localhost}
  port: ${DB_PORT:-3306}
  user: ${DB_USER}
  password: ${DB_PASSWORD}
  useSSL: false
  useLegacyDatetimeCode: false
  allowPublicKeyRetrieval: true

jaeger:
  serviceName: noti

logging:
  level: INFO

kafka:
    producer:
        acks: all
        bootstrap.servers:
            - 10.0.1.2:9092
        schema.registry.url: http://10.0.1.2:8081
        #buffer.memory:
        #compression.type:
        #retries:
        #batch.size:
        #linger.ms:
        #client.id:
        #max.in.flight.requests.per.connection:
        #timeout.ms.request.timeout.ms:
        #metadata.fetch.timeout.ms:
        #max.block.ms:
        #max.request.size:
        #receive.buffer.bytes:
        #send.buffer.bytes:

metrics:
  frequency: ${METRICS_FREQUENCY:-1 second}
  reporters:
    - type: graphite
      host: ${GRAPHITE_REPORTER_HOST:-localhost}
      port: ${GRAPHITE_REPORTER_PORT:-2003}
      prefix: noti
      durationUnit: ${GRAPHITE_REPORTER_DURATION_UNIT:-milliseconds}
      rateUnit: ${GRAPHITE_REPORTER_RATE_UNIT:-seconds}
