database:
  name: noti
  host: localhost
  port: 3306
  user: web_app
  password: __Goalie31__
  useSSL: false
  useLegacyDatetimeCode: false

sms:
  accountSID: AC4c180ac085f2322e4882f9a49e5a8b80
  authToken: 26e2ed186d8ea15fcb1630f64700437d

jaeger:
  serviceName: noti

logging:
  level: INFO

metrics:
  frequency: 1 second
  reporters:
    - type: graphite
      host: localhost
      port: 2003
      #prefix: <prefix>
