version: "3"
services:
    noti:
        build:
            context: ../
            dockerfile: ./docker/Dockerfile
        env_file:
            ./noti.env
        ports:
            - "8080:8080"
    noti-db:
        image: mysql
        env_file:
            ./db.env
        ports:
            - "3306:3306"
        volumes:
          - ./mysql/:/etc/mysql/conf.d
          - ./mysql_startup_scripts/:/docker-entrypoint-initdb.d

