version: "3"
services:
    noti:
        build:
            context: ../
            dockerfile: ./docker/Dockerfile
        env_file:
            ./noti.env
        ports:
            - "9090:8080"
            - "9091:8081"
        depends_on:
            - "noti-db"
            - "graphite"
    noti-db:
        image: mysql
        restart: always
        env_file:
            ./db.env
        volumes:
          - ./mysql/:/etc/mysql/conf.d
          - ./mysql_startup_scripts/:/docker-entrypoint-initdb.d
    graphite:
        image: graphiteapp/graphite-statsd
        restart: always
        ports:
          - "80:80"
          - "2003-2004:2003-2004"
          - "2023-2024:2023-2024"
          - "8126:8126"
          - "8125:8125/udp"  
    grafana:
        image: grafana/grafana
        restart: always
        ports:
          - "3000:3000"
    jaegar:
        image: jaegertracing/all-in-one:1.6
        ports:
            - "5775:5775/udp"
            - "6831:6831/udp"
            - "6832:6832/udp"
            - "5778:5778"
            - "16686:16686"
            - "14268:14268"
            - "9411:9411"

