version: '3'
services:
  noti:
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
    env_file: ./noti.env
    ports:
      - '9090:8080'
      - '9091:8081'
    depends_on:
      - noti-db
      - graphite
  noti-db:
    image: mysql
    restart: always
    env_file: ./db.env
    volumes:
      - './mysql/:/etc/mysql/conf.d'
      - './mysql_startup_scripts/:/docker-entrypoint-initdb.d'
  graphite:
    image: graphiteapp/graphite-statsd
    restart: always
    ports:
      - '80:80'
  grafana:
    image: grafana/grafana
    restart: always
    ports:
      - '3000:3000'
  jaegar:
    image: 'jaegertracing/all-in-one:1.6'
    ports:
      - '16686:16686'
  kafka:
    image: spotify/kafka
    restart: always
    env_file: ./kafka.env
  schema-registry:
    image: 'confluentinc/cp-schema-registry:4.1.0'
    restart: always
    env_file: ./schema-registry.env
    depends_on:
      - kafka
  noti-consumer:
    image: 'freerjm/noti-consumer:wip'
    restart: always
    env_file: ./noti-consumer.env
    depends_on:
      - kafka
      - schema-registry

