CREATE TABLE `NOTIFICATION_TARGET`
(
	`NOTIFICATION_UUID`	VARCHAR(128)	NOT NULL,
	`TARGET_UUID`		VARCHAR(128)	NOT NULL,

	PRIMARY KEY(`NOTIFICATION_UUID`, `TARGET_UUID`),
	CONSTRAINT FOREIGN KEY `NOTIFICATION_TARGET_NOTIFICATION_UUID_FK` (`NOTIFICATION_UUID`) REFERENCES `NOTIFICATION` (`UUID`),
	CONSTRAINT FOREIGN KEY `NOTIFICATION_TARGET_TARGET_UUID_FK` (`TARGET_UUID`) REFERENCES `TARGET` (`UUID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
