CREATE TABLE `REPRESENTATION_METADATA`
(
	`UUID`						VARCHAR(128)	NOT NULL,
	`CONTENT_LOCATION`			VARCHAR(2048)	NOT NULL,
	`CONTENT_LOCATION_HASH`		VARCHAR(128)	NOT NULL,
	`CONTENT_TYPE`				VARCHAR(128)	NOT NULL,
	`CONTENT_LANGUAGE`			VARCHAR(128)	NULL,
	`CONTENT_ENCODING`			VARCHAR(128)	NULL,
	`LAST_MODIFIED`				DATETIME		NOT NULL,
	`ENTITY_TAG`				VARCHAR(128)	NOT NULL,
	
	PRIMARY KEY(`UUID`),
	UNIQUE KEY(`CONTENT_LOCATION_HASH`, `CONTENT_TYPE`, `CONTENT_LANGUAGE`, `CONTENT_ENCODING`)
)  ENGINE=InnoDB DEFAULT CHARSET=utf8;
