CREATE TABLE `RESOURCE_METADATA`
(
	`URI`			VARCHAR(1024)	NOT NULL,
	`URI_HASH`		VARCHAR(128)		NOT NULL,
	`CONTENT_TYPE`	VARCHAR(128)		NOT NULL,
	`LAST_MODIFIED`	DATETIME			NOT NULL,
	`ENTITY_TAG`		VARCHAR(1024)	NOT NULL,
	`NODE_NAME`		VARCHAR(128)		NOT NULL,
	`REVISION`		BIGINT			NOT NULL,
	
	PRIMARY KEY(`URI_HASH`, `CONTENT_TYPE`)
)  ENGINE=InnoDB DEFAULT CHARSET=utf8;
