CREATE TABLE `MESSAGE`
(
	`ID`				BIGINT			NOT NULL,
	`FROM`				VARCHAR(128)	NOT NULL,
	`TO`				VARCHAR(128)	NOT NULL,
	`CONTENT`			VARCHAR(2048)	NOT NULL,
	`STATUS`			VARCHAR(128)	NOT NULL,
	`NOTIFICATION_UUID`	VARCHAR(128)	NOT NULL,
	`EXTERNAL_ID`		VARCHAR(128)	NOT NULL,

	PRIMARY KEY(`NOTIFICATION_UUID`, `ID`),
	CONSTRAINT FOREIGN KEY `MESSAGE_NOTIFICATION_UUID` (`NOTIFICATION_UUID`) REFERENCES `NOTIFICATION` (`UUID`)

) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
