CREATE TABLE `AUDIENCE`
(
	`UUID`		VARCHAR(128)		NOT NULL,
	`NAME`		VARCHAR(128)		NOT NULL,

	PRIMARY KEY(`UUID`),
	CONSTRAINT UNIQUE `AUDIENCE_NAME_UK` (`NAME`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
