CREATE TABLE `RESOURCE_METADATA`
(
	`URI`			VARCHAR(512)	NOT NULL, -- create a column that is a hash of URI and use that.
	`CONTENT_TYPE`	VARCHAR(128)		NOT NULL,
	`LAST_MODIFIED`	DATETIME			NOT NULL,
	`ENTITY_TAG`		VARCHAR(1024)	NOT NULL,
	
	PRIMARY KEY(`URI`, `CONTENT_TYPE`)
)  ENGINE=InnoDB DEFAULT CHARSET=utf8;
