CREATE TABLE `NOTIFICATION_AUDIENCE`
(
	`NOTIFICATION_UUID`		VARCHAR(128)		NOT NULL,
	`AUDIENCE_UUID`			VARCHAR(128)		NOT NULL,
	
	PRIMARY KEY(`NOTIFICATION_UUID`, `AUDIENCE_UUID`),
	CONSTRAINT FOREIGN KEY `NOTIFICATION_AUDIENCE_NOTIFICATION_UUID_FK` (`NOTIFICATION_UUID`) REFERENCES `NOTIFICATION` (`UUID`),
	CONSTRAINT FOREIGN KEY `NOTIFICATION_AUDIENCE_AUDIENCE_UUID_FK` (`AUDIENCE_UUID`) REFERENCES `AUDIENCE` (`UUID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;