CREATE TABLE `AUDIENCE_TARGET`
(
	`AUDIENCE_UUID`		VARCHAR(128)		NOT NULL,
	`TARGET_UUID`		VARCHAR(128)		NOT NULL,
	
	PRIMARY KEY(`AUDIENCE_UUID`, `TARGET_UUID`),
	CONSTRAINT `AUDIENCE_TARGET_AUDIENCE_UUID_FK` FOREIGN KEY (`AUDIENCE_UUID`) REFERENCES `AUDIENCE` (`UUID`),
	CONSTRAINT `AUDIENCE_TARGET_TARGET_UUID_FK` FOREIGN KEY (`TARGET_UUID`) REFERENCES `TARGET` (`UUID`)
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;